services:
  redis:
    image: redis/redis-stack:7.2.0-v14
    container_name: redis
    ports:
      - '6379:6379'
      - '8001:8001'
    environment:
      REDIS_ARGS: '--requirepass ${REDIS_PASSWORD} --save 20 1 --loglevel warning'
    command: ['/entrypoint.sh', './conf/redis-stack.conf']
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', 'ping']
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:8.0.6
    container_name: mongo
    hostname: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./data/mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - ./data/mongo/backup:/backup

volumes:
  redis_data:
    driver: local
  mongo_data:
    driver: local
